CREATE TABLE BAKEOFF (
	ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    BO_DATE DATE UNIQUE,
    FOOD VARCHAR(28)
);

CREATE TABLE BAKER (
	ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    BAKER_NAME VARCHAR(28) UNIQUE
);

CREATE TABLE JUDGE (
	ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    JUDGE_NAME VARCHAR(28) UNIQUE
);

CREATE TABLE PARTICIPANT (
	ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    FK_BAKER_ID INT,
    FK_BAKEOFF_ID INT,
    ENTRANT_ID INT,
    DESCRIPTION VARCHAR(256),
    FOREIGN KEY (FK_BAKER_ID) REFERENCES BAKER (ID),
    FOREIGN KEY (FK_BAKEOFF_ID) REFERENCES BAKEOFF (ID),
    CONSTRAINT UC_Participant UNIQUE (FK_BAKER_ID, FK_BAKEOFF_ID, ENTRANT_ID)
);

CREATE TABLE JUDGE_HISTORY (
	ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    FK_JUDGE_ID INT,
    FK_BAKEOFF_ID INT,
    FOREIGN KEY (FK_JUDGE_ID) REFERENCES JUDGE (ID),
    FOREIGN KEY (FK_BAKEOFF_ID) REFERENCES BAKEOFF (ID),
    CONSTRAINT UC_Judge_History UNIQUE (FK_JUDGE_ID, FK_BAKEOFF_ID)
);

CREATE TABLE RESULT (
	ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    FK_PARTICIPANT_ID INT,
    FK_JUDGE_ID INT,
    APPEARANCE INTEGER,
    TASTE INTEGER,
    FOREIGN KEY (FK_PARTICIPANT_ID) REFERENCES PARTICIPANT (ID),
    FOREIGN KEY (FK_JUDGE_ID) REFERENCES JUDGE (ID),
    CONSTRAINT UC_Result UNIQUE (FK_PARTICIPANT_ID, FK_JUDGE_ID)
);