spring:
  main:
    banner-mode: off
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:${JAWSDB_URL:mysql://localhost:30306/bakeoff?serverTimezone=UTC}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:password}
    hikari:
      maximum-pool-size: 5
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  security:
    user:
      name: BAKEOFF_USER
      password: ${BAKEOFF_USER_PASSWORD:test}
      roles: USER
  servlet:
    multipart:
      max-file-size: 50MB
server:
  port: 8090
  tomcat:
    accesslog:
      enabled: true
      pattern: '{
      "@timestamp":"%{begin:yyyy-MM-dd}tT%{begin:HH:mm:ss.SSSZ}t",
      "responseBytes":"%b",
      "protocol":"%H",
      "method":"%m",
      "responseStatus":%s,
      "urlPath":"%U",
      "responseTime":%D,
      "processingTime":%F,
      "correlationId":"%{Correlation-Id}i",
      "userAgent":"%{User-Agent}i"}'
      directory: /dev
      suffix:
      prefix: "stdout"
      file-date-format:
  ssl:
    enabled: false

aws:
  bucketName: ${AWS_BUCKET_NAME:test-bucket}
  accessKey: ${AWS_ACCESS_KEY:test}
  secretKey: ${AWS_SECRET_KEY:test}
  region: ${AWS_REGION:eu-west-1}
  endpoint: ${AWS_ENDPOINT:http://localhost:30081}

securedroutes:
  unsecured: ["/bakeoff", "/bakeoff/latest", "/bakeoff/totals", "/aws/download/**"]
  secured: ["/bakeoff/**", "/aws/**"]