name: Bakeoff API Build Plan

on:
  push:
    branches: [ master, feature/** ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Step 1 - Checkout main branch from GitHub
      uses: actions/checkout@v3
      
    - name: Step 2 - Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven

    - name: Step 3 - Start DB
      uses: shogo82148/actions-setup-mysql@v1
      with:
        mysql-version: '8.0'
        root-password: password

    - name: Step 4 - Setup DB
      run: |
        mysql -uroot -h127.0.0.1 -ppassword -e 'CREATE DATABASE bakeoff'
        mysql -uroot -h127.0.0.1 -ppassword bakeoff < schema.sql

    - name: Step 5 - Build with Maven
      run: mvn clean install
