name: Bakeoff API Build Plan

on:
  push:
    branches: [ main, feature/**, bugfix/** ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Step 1 - Checkout main branch from GitHub
      uses: actions/checkout@v3
      
    - name: Step 2 - Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven

    - name: Step 3 - Start DB
      uses: shogo82148/actions-setup-mysql@v1
      with:
        mysql-version: '8.0'
        root-password: password

    - name: Step 4 - Setup DB
      run: |
        mysql -uroot -h127.0.0.1 -ppassword -e 'CREATE DATABASE bakeoff'
        mysql -uroot -h127.0.0.1 -ppassword bakeoff < schema.sql

    - name: Step 5 - Build with Maven
      run: mvn clean install

  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Step 6 - Checkout for release to Herkou
        uses: actions/checkout@v2

      - name: Step 7 - Release to heroku
        uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "bakeoff-api" #Must be unique in Heroku
          heroku_email: ${{secrets.HEROKU_EMAIL}}
